### ISSUE TITLE
error while running the demo

### ISSUE THREAD

**Issue by ghost** [yuxng/PoseCNN#113]
Hi

I have compiled all the packages and when I run the demo file I get the following error. Do you know what might cause the problem?

```
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=1
+ CUDA_VISIBLE_DEVICES=1
+ ./tools/demo.py --gpu 1 --network vgg16_convs --model data/demo_models/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000.ckpt --imdb lov_keyframe --cfg experiments/cfgs/lov_color_2d.yml --rig data/LOV/camera.json --cad data/LOV/models.txt --pose data/LOV/poses.txt --background data/cache/backgrounds.pkl
Traceback (most recent call last):
  File "./tools/demo.py", line 13, in <module>
    from fcn.test import test_net_images
  File "/home/mohammad/Mohammad_ws/PoseCNN/tools/../lib/fcn/test.py", line 29, in <module>
    from normals import gpu_normals
ImportError: /home/mohammad/Mohammad_ws/PoseCNN/tools/../lib/normals/gpu_normals.so: undefined symbol: cudaSetupArgument
```

Ubuntu 16
Cuda 9.0
cudnn 7.0
GPU: Geforce RTX 2080 ti
Tensorflow 1.8

**Comment by ghost** [comment]
I found the reason. The problem was that I was using tensorflow 1.8 instead of tensorflow-gpu 1.8 in conda.
