### ISSUE TITLE
ImportError while Running the demo

### ISSUE THREAD

**Issue by zgl1113** [yuxng/PoseCNN#15]
when Running the demo:

`./experiments/scripts/demo.sh --gpu 0`

I got the following error:

ImportError: /home/zgl/PoseCNN/tools/../lib/synthesize/synthesizer.so: undefined symbol: _ZN11SynthesizerC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_

anyone has gotten the same error and solved it?

**Comment by yuxng** [comment]
I have updated the code to another version. Can you try a git pull and try it again?

**Comment by zgl1113** [comment]
Hi Yu Xiang, @yuxng 
Thanks a lot  for replying and providing the code for your paper!
1.I have downloaded the updated code and tried it again.This time（I skip compiling lib/synthesize） ,when I running the demo:`./experiments/scripts/demo.sh --gpu 0`,I got a different error:

Traceback (most recent call last):
  File "./tools/demo.py", line 13, in <module>
    from fcn.test import test_net_images
  File "/home/zgl/PoseCNN/tools/../lib/fcn/test.py", line 18, in <module>
    from utils.nms_wrapper import nms
  File "/home/zgl/PoseCNN/tools/../lib/utils/nms_wrapper.py", line 12, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

 Do you know why this is happening?

2.As you pointed out in your paper,PoseCNN uses ICP to refine the 6D pose.So I wonder which parts of lib are specifically used for refinement.Are `pose_refinement` and ` synthesize`?

Thank you again for your great work.Looking forward to your reply.

**Comment by mcimpoi** [comment]
> File "/home/zgl/PoseCNN/tools/../lib/utils/nms_wrapper.py", line 12, in 
from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

`sudo pip install cython` or
`conda install cython`
then, from $ROOT/lib:
`python setup.py build_ext --inplace`

In the current version, you might have to comment out the Extension(synthesizer...) in the setup.py file, as that one files to compile (synthesize/synthesizer.cpp:588:27: fatal error: synthesizer.hpp: No such file or directory), but apart from that, this fixes the gpu_nms issue.

**Comment by LucasdeSouzaAlbuquerque** [comment]
Hello! I'm having a similar problem when running the demo. Weirdly enough, I was having the 'no module named gpu_nms' problem *before* doing the latest pull and now I'm getting the following error:

```
__File "/home/lucas-albuquerque/Desktop/PoseCNN/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/home/lucas-albuquerque/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/lucas-albuquerque/Desktop/PoseCNN/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3___
```
If anyone has a solution and could help that'd be wonderful. Thanks in advance!
(My tensorflow version is 1.8. & my CUDA is 9.0, though I got the same error when I downgraded to other TF versions)

**Comment by hridaybavle** [comment]
Hi all, I am having the same error with CUDA 9.0 and tensorflow 1.8 GPU not built by source. 

tensorflow.python.framework.errors_impl.NotFoundError: /home/hriday/workspace/PoseCNN/PoseCNN/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

Has anyone solved the error?

**Comment by TotoLulu94** [comment]
@hridaybavle I have the same error, could you explain what you mean by "building tensorflow by source." ?

**Comment by saurabheights** [comment]
Check this to find gcc version used - https://www.tensorflow.org/versions/master/install/install_sources

I installed tensorflow using conda, so probably it used gcc-4.8

Now, my gcc -version was 5.4, which means my tensorflow is compiled using gcc-4.8 and I am compiling the lib code using gcc-5.4 which is causing the error, atleast in my case.

To fix this, install gcc-4.8, you should have /usr/bin/gcc-4.8 and /usr/bin/g++-4.8 after that. This error will still happen, because when our `ll /usr/bin/gcc` is still pointed to gcc-5.4.

Now, change the softlink to :-

` sudo ln -sf /usr/bin/gcc-4.8 `/usr/bin/gcc``
` sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++`

Now, check `gcc --version` and `g++ --version` and if they are at 4.8 do:


`cd PoseCNN/lib`
`./make.sh && git clean -f &&  python setup.py build_ext --inplace && cd .. && ./experiments/scripts/demo.sh 0`

**NOTE**: `git clean -f` removes  any untracked file so dont run it and just delete below given files manually. Or run `git clean -n` to check what will `git clean -f` delete without deleting anything. It should be following files only:

`rm lib/nms/gpu_nms.cpp`
`rm lib/normals/gpu_normals.cpp`

**Comment by koki0702** [comment]
I got the error below when running the demo.

```
...
 File "./tools/demo.py", line 13, in <module>
    from fcn.test import test_net_images
  File "/PoseCNN/tools/../lib/fcn/test.py", line 29, in <module>
    from normals import gpu_normals
ImportError: cannot import name gpu_normals
```

Where can I install `normals`?

BTW, This is my Dockerfile.
```
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update
RUN apt-get install python-pip python-dev python-pip python-dev git curl libglib2.0-0 libsm6 libxext6 libgtk2.0-dev -y
RUN pip install tensorflow-gpu opencv-python easydict scipy transforms3d

RUN git clone https://github.com/yuxng/PoseCNN.git

WORKDIR PoseCNN/lib

RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
RUN LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/:$LD_LIBRARY_PATH sh make.sh

# download VGG-16.npy
RUN curl -c /tmp/cookie.txt -s -L "https://drive.google.com/uc?export=download&id=1UdmOKrr9t4IetMubX-y-Pcn7AVaWJ2bL" |grep confirm |  sed -e\
 "s/^.*confirm=\(.*\)&amp;id=.*$/\1/" | xargs -I{} curl -b /tmp/cookie.txt  -L -o vgg16.npy "https://drive.google.com/uc?confirm={}&export=d\
ownload&id=1UdmOKrr9t4IetMubX-y-Pcn7AVaWJ2bL"
RUN mv vgg16.npy /PoseCNN/data/imagenet_models/

# dwonload model
RUN curl -c /tmp/cookie.txt -s -L "https://drive.google.com/uc?export=download&id=1UNJ56Za6--bHGgD3lbteZtXLC2E-liWz" |grep confirm |  sed -e\
 "s/^.*confirm=\(.*\)&amp;id=.*$/\1/" | xargs -I{} curl -b /tmp/cookie.txt  -L -o demo_models.zip "https://drive.google.com/uc?confirm={}&ex\
port=download&id=1UNJ56Za6--bHGgD3lbteZtXLC2E-liWz"
RUN mv demo_models.zip /PoseCNN/data/demo_models

WORKDIR /PoseCNN
RUN ./experiments/scripts/demo.sh 0
```

**Comment by hridaybavle** [comment]
check issue #25

**Comment by saurabheights** [comment]
@koki0702 If you get ICP and training module, i.e.  PoseCNN/lib/synthesize to work with DockerFile, please do upload it. Was planning to resolve my build issues with Docker and it would really save a lot of time. Thank you in advance.

**Comment by saurabheights** [comment]
@koki0702 : normals is code in PoseCNN itself, you have to build library for that code. See issue #25.

**Comment by koki0702** [comment]
@saurabheights 
As you suggested, I used g++4.8.
But i got the error below.
Any idea?

```
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/normals/compute_normals.o build/temp.linux-x86_64-2.7/normals/gpu_normals.o -L/usr/local/cuda/lib64 -Wl,-R/usr/local/cuda/lib64 -lcudart -o /PoseCNN/lib/normals/gpu_normals.so
c++: error: unrecognized command line option '-Wdate-time'
c++: error: unrecognized command line option '-fstack-protector-strong'
c++: error: unrecognized command line option '-Wdate-time'
c++: error: unrecognized command line option '-fstack-protector-strong'
error: command 'c++' failed with exit status 1
```

**Comment by saurabheights** [comment]
@koki0702 Hi, this seems to be a different issue.  The option -fstack-protector-strong is not available in gcc-4.8. Not sure where is this getting enabled.

P.S. I am working on DockerFile for now. Will update if successful.

**Comment by koki0702** [comment]
@saurabheights 
I managed to create a Dockerfile for demo.py.

https://gist.github.com/koki0702/1b5ee259ba688cd2aee7b644190e5813

**Comment by aniruddhavpatil** [comment]
@saurabheights @koki0702 
I tried running this dockerfile with docker build -f and got the following message:
`Step 6/53 : COPY jupyter_notebook_config.py /root/.jupyter/`
`COPY failed: stat /var/lib/docker/tmp/docker-builder104820317/jupyter_notebook_config.py: no such file or directory`

Am I doing something wrong?

**Comment by huckl3b3rry87** [comment]
just comment out that line
