### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: undefined symbol: nlopt_destroy

### ISSUE THREAD

**Issue by QuanNguyen94** [yuxng/PoseCNN#19]
Hi Yu Xiang,
I have compiled successfully all your installation steps and I run this './experiments/scripts/demo.sh $GPU_ID' . However, I get the trouble: 

`Traceback (most recent call last):
  File "./tools/demo.py", line 113, in <module>
    from networks.factory import get_network
  File "/home/quannguyen/quan/Solomon/python/Deep Learning/PoseCNN-master/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/quannguyen/quan/Solomon/python/Deep Learning/PoseCNN-master/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/quannguyen/quan/Solomon/python/Deep Learning/PoseCNN-master/tools/../lib/networks/network.py", line 17, in <module>
    import hough_voting_layer.hough_voting_op as hough_voting_op
  File "/home/quannguyen/quan/Solomon/python/Deep Learning/PoseCNN-master/tools/../lib/hough_voting_layer/hough_voting_op.py", line 5, in <module>
    _hough_voting_module = tf.load_op_library(filename)
  File "/home/quannguyen/anaconda3/envs/CV_TF_python36/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/quannguyen/quan/Solomon/python/Deep Learning/PoseCNN-master/tools/../lib/hough_voting_layer/hough_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: nlopt_destroy`

I have searched this issue and see this #1 which may be same as mine, but I don't know where make.sh file is in the repo, can you show me ?
Thanks.

**Comment by krips89** [comment]
I have the same problem. What solution from #1  fixed it?
D_GLIBCXX_USE_CXX11_ABI=0?
I get the error even with this flag.

**Comment by iris0329** [comment]
＠QuanNguyen94　hello? could you tell me how to solve the problem? i add the flag in the command, but still have error.
do u compile tensorflow from source code?
