### ISSUE TITLE
yaml.constructor.ConstructorError: could not determine a constructor for the tag

### ISSUE THREAD

**Issue by nkalavak** [yuxng/PoseCNN#27]
I am trying to run the demo and run into the following issue on my Ubuntu 16.04 machine. 

Called with args:
Namespace(background_name='data/cache/backgrounds.pkl', cad_name='data/LOV/models.txt', cfg_file='experiments/cfgs/lov_color_2d.yml', gpu_id=0, imdb_name='lov_keyframe', kfusion=False, model='data/demo_models/vgg16_fcn_color_single_frame_2d_pose_add_lov_iter_160000.ckpt', network_name='vgg16_convs', pose_name='data/LOV/poses.txt', pretrained_model=None, rig_name='data/LOV/camera.json', wait=True)
Traceback (most recent call last):
  File "./tools/demo.py", line 77, in <module>
    cfg_from_file(args.cfg_file)
  File "/home/nivedithak/Downloads/PoseCNN-master/tools/../lib/fcn/config.py", line 303, in cfg_from_file
    yaml_cfg = edict(yaml.load(f))
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/__init__.py", line 74, in load
    return loader.get_single_data()
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/home/nivedithak/Downloads/PoseCNN-master/PYTHON_27/local/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "experiments/cfgs/lov_color_2d.yml", line 12, column 16

I don't see any unusual characters in that line and it is using the python specific tag `!!python/tuple`.

**Comment by TotoLulu94** [comment]
Which version of YAML are you using ? I downgraded PyYAML from 4.1 to 3.12 typing
`pip install PyYAML==3.12`
and it worked well.

**Comment by nkalavak** [comment]
That totally did it! I had version 4.1 too.
