### ISSUE TITLE
Error Running demo.sh

### ISSUE THREAD

**Issue by TotoLulu94** [yuxng/PoseCNN#29]
I am trying to run the demo : 
`./experiments/scripts/demo.sh $GPU_ID`
but I get the following error : 
```
Traceback (most recent call last):
  File "./tools/demo.py", line 84, in <module>
    imdb = get_imdb(args.imdb_name)
  File "/home/thomas/Desktop/PoseCNN-master/tools/../lib/datasets/factory.py", line 116, in get_imdb
    return __sets[name]()
  File "/home/thomas/Desktop/PoseCNN-master/tools/../lib/datasets/factory.py", line 57, in <lambda>
    datasets.lov(split))
  File "/home/thomas/Desktop/PoseCNN-master/tools/../lib/datasets/lov.py", line 55, in __init__
    'Data path does not exist: {}'.format(self._data_path)
AssertionError: Data path does not exist: /home/thomas/Desktop/PoseCNN-master/tools/../lib/datasets/../../data/LOV/data
```
If I get it right, it's trying to acces to a folder **data** that does not exist. Am I suppose to create it ? If yes, should I fill it and with what ?

**Comment by youkenhou** [comment]
Did you solve this problem by creating an empty folder **data**? I met the same problem and creating an empty folder works but I'm wondering if there is any further effect. Thanks.

**Comment by koki0702** [comment]
I met the same problem.
Do you know the solution?

**Comment by TotoLulu94** [comment]
Yes, I just created an empty folder "data" to solve this issue. But I don't know if there's any further effect.
