### ISSUE TITLE
synthesizer argument error (python argument type does not match c++)

### ISSUE THREAD

**Issue by mohammad200h** [yuxng/PoseCNN#37]
Hi 
I was trying to run the training shell script: ./experiments/scripts/lov_color_2d_train.sh 0
When it runs it stops at render function and gives me this error: I guess it has problems matching str in python to string in c++ which could be cython error.
"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./tools/train_net.py", line 160, in render
    synthesizer = libsynthesizer.Synthesizer(cfg.CAD, cfg.POSE )
ArgumentError: Python argument types in
    Synthesizer.__init__(Synthesizer, str, str)
did not match C++ signature:
    __init__(_object*, std::string, std::string)
"

The whole log file is attached:`+ echo Logging output to experiments/logs/lov_color_2d_train.txt.2018-07-10_15-39-28
Logging output to experiments/logs/lov_color_2d_train.txt.2018-07-10_15-39-28
+ export LD_PRELOAD=/usr/lib/libtcmalloc.so.4
+ LD_PRELOAD=/usr/lib/libtcmalloc.so.4
+ ./tools/train_net.py --gpu 0 --network vgg16_convs --weights data/imagenet_models/vgg16.npy --imdb lov_train --cfg experiments/cfgs/lov_color_2d.yml --cad data/LOV/models.txt --pose data/LOV/poses.txt --iters 160000
shapenet_scene_train
shapenet_scene_val
shapenet_single_train
shapenet_single_val
gmu_scene_train
gmu_scene_val
rgbd_scene_train
rgbd_scene_val
rgbd_scene_trainval
lov_train
lov_val
lov_keyframe
lov_trainval
lov_debug
lov_train_few
lov_val_few
lov_single_002_master_chef_can_train
lov_single_002_master_chef_can_val
lov_single_002_master_chef_can_keyframe
lov_single_003_cracker_box_train
lov_single_003_cracker_box_val
lov_single_003_cracker_box_keyframe
lov_single_004_sugar_box_train
lov_single_004_sugar_box_val
lov_single_004_sugar_box_keyframe
lov_single_005_tomato_soup_can_train
lov_single_005_tomato_soup_can_val
lov_single_005_tomato_soup_can_keyframe
lov_single_006_mustard_bottle_train
lov_single_006_mustard_bottle_val
lov_single_006_mustard_bottle_keyframe
lov_single_007_tuna_fish_can_train
lov_single_007_tuna_fish_can_val
lov_single_007_tuna_fish_can_keyframe
lov_single_008_pudding_box_train
lov_single_008_pudding_box_val
lov_single_008_pudding_box_keyframe
lov_single_009_gelatin_box_train
lov_single_009_gelatin_box_val
lov_single_009_gelatin_box_keyframe
lov_single_010_potted_meat_can_train
lov_single_010_potted_meat_can_val
lov_single_010_potted_meat_can_keyframe
lov_single_011_banana_train
lov_single_011_banana_val
lov_single_011_banana_keyframe
lov_single_019_pitcher_base_train
lov_single_019_pitcher_base_val
lov_single_019_pitcher_base_keyframe
lov_single_021_bleach_cleanser_train
lov_single_021_bleach_cleanser_val
lov_single_021_bleach_cleanser_keyframe
lov_single_024_bowl_train
lov_single_024_bowl_val
lov_single_024_bowl_keyframe
lov_single_025_mug_train
lov_single_025_mug_val
lov_single_025_mug_keyframe
lov_single_035_power_drill_train
lov_single_035_power_drill_val
lov_single_035_power_drill_keyframe
lov_single_036_wood_block_train
lov_single_036_wood_block_val
lov_single_036_wood_block_keyframe
lov_single_037_scissors_train
lov_single_037_scissors_val
lov_single_037_scissors_keyframe
lov_single_040_large_marker_train
lov_single_040_large_marker_val
lov_single_040_large_marker_keyframe
lov_single_051_large_clamp_train
lov_single_051_large_clamp_val
lov_single_051_large_clamp_keyframe
lov_single_052_extra_large_clamp_train
lov_single_052_extra_large_clamp_val
lov_single_052_extra_large_clamp_keyframe
lov_single_061_foam_brick_train
lov_single_061_foam_brick_val
lov_single_061_foam_brick_keyframe
ycb_trainval
ycb_single_002_master_chef_can_train
ycb_single_003_cracker_box_train
ycb_single_004_sugar_box_train
ycb_single_005_tomato_soup_can_train
ycb_single_006_mustard_bottle_train
ycb_single_007_tuna_fish_can_train
ycb_single_008_pudding_box_train
ycb_single_009_gelatin_box_train
ycb_single_010_potted_meat_can_train
ycb_single_011_banana_train
ycb_single_019_pitcher_base_train
ycb_single_021_bleach_cleanser_train
ycb_single_024_bowl_train
ycb_single_025_mug_train
ycb_single_035_power_drill_train
ycb_single_036_wood_block_train
ycb_single_037_scissors_train
ycb_single_040_large_marker_train
ycb_single_051_large_clamp_train
ycb_single_052_extra_large_clamp_train
ycb_single_061_foam_brick_train
yumi_train
linemod_ape_train
linemod_ape_test
linemod_ape_train_few
linemod_ape_test_few
linemod_benchvise_train
linemod_benchvise_test
linemod_benchvise_train_few
linemod_benchvise_test_few
linemod_bowl_train
linemod_bowl_test
linemod_bowl_train_few
linemod_bowl_test_few
linemod_camera_train
linemod_camera_test
linemod_camera_train_few
linemod_camera_test_few
linemod_can_train
linemod_can_test
linemod_can_train_few
linemod_can_test_few
linemod_cat_train
linemod_cat_test
linemod_cat_train_few
linemod_cat_test_few
linemod_cup_train
linemod_cup_test
linemod_cup_train_few
linemod_cup_test_few
linemod_driller_train
linemod_driller_test
linemod_driller_train_few
linemod_driller_test_few
linemod_duck_train
linemod_duck_test
linemod_duck_train_few
linemod_duck_test_few
linemod_eggbox_train
linemod_eggbox_test
linemod_eggbox_train_few
linemod_eggbox_test_few
linemod_glue_train
linemod_glue_test
linemod_glue_train_few
linemod_glue_test_few
linemod_holepuncher_train
linemod_holepuncher_test
linemod_holepuncher_train_few
linemod_holepuncher_test_few
linemod_iron_train
linemod_iron_test
linemod_iron_train_few
linemod_iron_test_few
linemod_lamp_train
linemod_lamp_test
linemod_lamp_train_few
linemod_lamp_test_few
linemod_phone_train
linemod_phone_test
linemod_phone_train_few
linemod_phone_test_few
sym_train
Called with args:
Namespace(cad_name='data/LOV/models.txt', cfg_file='experiments/cfgs/lov_color_2d.yml', gpu_id=0, imdb_name='lov_train', max_iters=160000, network_name='vgg16_convs', pose_name='data/LOV/poses.txt', pretrained_ckpt=None, pretrained_model='data/imagenet_models/vgg16.npy', randomize=False, rig_name=None)
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'BACKGROUND': '',
 'CAD': '',
 'EPS': 1e-14,
 'EXP_DIR': 'lov',
 'FEATURE_STRIDE': 16,
 'FLIP_X': False,
 'GPU_ID': 0,
 'INPUT': 'COLOR',
 'NETWORK': 'VGG16',
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POSE': '',
 'RIG': '',
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/mamad/PoseCNN',
 'TEST': {'BBOX_REG': True,
          'GAN': False,
          'GRID_SIZE': 256,
          'NMS': 0.3,
          'POSE_REFINE': False,
          'POSE_REG': True,
          'RANSAC': False,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES_BASE': [1.0],
          'SEGMENTATION': True,
          'SINGLE_FRAME': True,
          'SYNTHETIC': False,
          'VERTEX_REG_2D': True,
          'VERTEX_REG_3D': False,
          'VISUALIZE': True,
          'VOTING_THRESHOLD': -1},
 'TRAIN': {'ADAPT': False,
           'ADAPT_NUM': 400,
           'ADAPT_RATIO': 1,
           'ADAPT_ROOT': '',
           'ADAPT_WEIGHT': 0.1,
           'ADD_NOISE': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'CHROMATIC': True,
           'DISPLAY': 20,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'GAN': False,
           'GRID_SIZE': 256,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 2,
           'LABEL_W': 1.0,
           'LEARNING_RATE': 0.001,
           'MATCHING': False,
           'MOMENTUM': 0.9,
           'NUM_CLASSES': 22,
           'NUM_STEPS': 5,
           'NUM_UNITS': 64,
           'OPTIMIZER': 'MOMENTUM',
           'POSE_REG': True,
           'POSE_W': 1.0,
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES_BASE': [1.0],
           'SEGMENTATION': True,
           'SINGLE_FRAME': True,
           'SNAPSHOT_INFIX': 'lov',
           'SNAPSHOT_ITERS': 10000,
           'SNAPSHOT_PREFIX': 'vgg16_fcn_color_single_frame_2d_pose_add',
           'STEPSIZE': 80000,
           'SYMSIZE': 0,
           'SYNITER': 0,
           'SYNNUM': 80000,
           'SYNROOT': 'data/LOV/data_syn/',
           'SYNTHESIZE': True,
           'SYN_CLASS_INDEX': -1,
           'SYN_HEIGHT': 480,
           'SYN_ONLINE': True,
           'SYN_RATIO': 5,
           'SYN_SAMPLE_OBJECT': True,
           'SYN_SAMPLE_POSE': True,
           'SYN_TFAR': 2.0,
           'SYN_TNEAR': 0.5,
           'SYN_WIDTH': 640,
           'THRESHOLD_LABEL': 1.0,
           'TRAINABLE': True,
           'USE_FLIPPED': False,
           'USE_GT': False,
           'VERTEX_REG_2D': True,
           'VERTEX_REG_3D': False,
           'VERTEX_W': 1.0,
           'VERTEX_W_INSIDE': 10.0,
           'VISUALIZE': False,
           'VOTING_THRESHOLD': -1,
           'WEIGHT_REG': 0.0001},
 'USE_GPU_NMS': True}
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/002_master_chef_can/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/003_cracker_box/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/004_sugar_box/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/005_tomato_soup_can/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/006_mustard_bottle/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/007_tuna_fish_can/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/008_pudding_box/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/009_gelatin_box/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/010_potted_meat_can/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/011_banana/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/019_pitcher_base/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/021_bleach_cleanser/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/024_bowl/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/025_mug/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/035_power_drill/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/036_wood_block/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/037_scissors/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/040_large_marker/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/051_large_clamp/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/052_extra_large_clamp/points.xyz
/home/mamad/PoseCNN/tools/../lib/datasets/../../data/LOV/models/061_foam_brick/points.xyz
Loaded dataset `lov_train` for training
symmetry
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
lov_train gt roidb loaded from /home/mamad/PoseCNN/data/cache/lov_train_gt_roidb.pkl
class weights:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Output will be saved to `/home/mamad/PoseCNN/output/lov/lov_train`
/gpu:0
registered Poly3
registered Poly3
registered Linear
registered Linear
Start Rendering ...
Start Rendering fn
('CAD ', <type 'str'>)
('pose ', <type 'str'>)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./tools/train_net.py", line 160, in render
    synthesizer = libsynthesizer.Synthesizer(cfg.CAD, cfg.POSE )
ArgumentError: Python argument types in
    Synthesizer.__init__(Synthesizer, str, str)
did not match C++ signature:
    __init__(_object*, std::string, std::string)

Tensor("fifo_queue_Dequeue:0", dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("conv4_3/conv4_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("score_conv4/score_conv4:0", shape=(?, ?, ?, 64), dtype=float32)
Tensor("upscore_conv5_1:0", shape=(?, ?, ?, 64), dtype=float32)
Tensor("upscore_1:0", shape=(?, ?, ?, 64), dtype=float32)
Tensor("score/score:0", shape=(?, ?, ?, 22), dtype=float32)
Tensor("div:0", shape=(?, ?, ?, 22), dtype=float32)
Tensor("fifo_queue_Dequeue:1", dtype=int32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("conv4_3/conv4_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("score_conv4_vertex/BiasAdd:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("upscore_conv5_vertex_1:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("ToInt32:0", shape=(?, ?, ?), dtype=int32)
Tensor("vertex_pred/BiasAdd:0", shape=(?, ?, ?, 66), dtype=float32)
Tensor("fifo_queue_Dequeue:6", dtype=float32)
Tensor("fifo_queue_Dequeue:7", dtype=float32)
Tensor("fifo_queue_Dequeue:5", dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("hough:0", shape=(?, 7), dtype=float32)
Tensor("conv4_3/conv4_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("hough:0", shape=(?, 7), dtype=float32)
RoiPool(top_data=<tf.Tensor 'pool5:0' shape=(?, 7, 7, 512) dtype=float32>, argmax=<tf.Tensor 'pool5:1' shape=(?, 7, 7, 512) dtype=int32>)
RoiPool(top_data=<tf.Tensor 'pool4_1:0' shape=(?, 7, 7, 512) dtype=float32>, argmax=<tf.Tensor 'pool4_1:1' shape=(?, 7, 7, 512) dtype=int32>)
Tensor("poses_tanh:0", shape=(?, 88), dtype=float32)
Tensor("hough:3", shape=(?, 88), dtype=float32)
Tensor("poses_pred:0", shape=(?, 88), dtype=float32)
Tensor("hough:2", shape=(?, 88), dtype=float32)
Tensor("hough:3", shape=(?, 88), dtype=float32)
Tensor("fifo_queue_Dequeue:8", dtype=float32)
Tensor("fifo_queue_Dequeue:9", dtype=float32)
Use network `vgg16_convs` in training
2018-07-10 15:39:32.228268: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-07-10 15:39:32.337709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:02:00.0
totalMemory: 11.90GiB freeMemory: 11.36GiB
2018-07-10 15:39:32.337748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
lov_train backgrounds loaded from /home/mamad/PoseCNN/data/cache/backgrounds.pkl
lov_train backgrounds depth loaded from /home/mamad/PoseCNN/data/cache/backgrounds_depth.pkl
Solving...
('Layer.py back', [])
Loading pretrained model weights from data/imagenet_models/vgg16.npy
conv5_1
conv5_1 weights assigned
conv5_1 biases assigned
fc6
fc6 weights assigned
fc6 biases assigned
conv5_3
conv5_3 weights assigned
conv5_3 biases assigned
fc7
fc7 weights assigned
fc7 biases assigned
fc8
conv5_2
conv5_2 weights assigned
conv5_2 biases assigned
conv4_1
conv4_1 weights assigned
conv4_1 biases assigned
conv4_2
conv4_2 weights assigned
conv4_2 biases assigned
conv4_3
conv4_3 weights assigned
conv4_3 biases assigned
conv3_3
conv3_3 weights assigned
conv3_3 biases assigned
conv3_2
conv3_2 weights assigned
conv3_2 biases assigned
conv3_1
conv3_1 weights assigned
conv3_1 biases assigned
conv1_1
conv1_1 weights assigned
conv1_1 biases assigned
conv1_2
conv1_2 weights assigned
conv1_2 biases assigned
conv2_2
conv2_2 weights assigned
conv2_2 biases assigned
conv2_1
conv2_1 weights assigned
conv2_1 biases assigned`

**Comment by renjiahao0928** [comment]
same error,have you solved it?

**Comment by mohammad200h** [comment]
Nope. Sorry:(
