### ISSUE TITLE
AttributeError: 'vgg16_convs' object has no attribute 'state'

### ISSUE THREAD

**Issue by TotoLulu94** [yuxng/PoseCNN#38]
Hi,
I got the above error when I try running 
`/experiments/scripts/lov_color_2d_test.sh 0`
And when I got into `/lib/networks/vgg16_convs.py`, there's indeed no attribute state. It is the same for weight and depth. The only network having these attributes is `vgg16`. However, when I input `--network vgg16` instead of `--network vgg16-convs`, it raises the error 
```
Traceback (most recent call last):
  File "./tools/test_net.py", line 105, in <module>
    network = get_network(args.network_name)
  File "/home/thomas/Desktop/Master_Project/PoseCNN/tools/../lib/networks/factory.py", line 50, in get_network
    raise KeyError('Unknown network: {}'.format(name))
KeyError: 'Unknown network: vgg16'
```
So I was wondering : what is the attribute ? what does it represent and where does it come from ?
How can I fix this ? 
Thank you

**Comment by mohammad200h** [comment]
Hey!

I am Mohammad Hamid. I am Phd student from  Automation and Manufacturing lab in UCL.I just noticed that you are using PoseCNN as well.  

I have made some progress with the PoseCNN set up and managed to run the demo, however I have not managed to  train the model. I was wandering if we could meet in person and have  a chat.

My email is: mohammad.hamid.16@ucl.ac.uk

Thanks 
Mohammad

**Comment by nkalavak** [comment]
I run into the same problem. Any leads on how to fix this?

**Comment by Abdul-Mukit** [comment]
@mohammad200h were you finally able to run the training? I was also able to run the demos, but most of the other tests in experiments/scripts don't work. Any advice would be very helpful.
What should I do to get them running?
