### ISSUE TITLE
Data folder not found while running the demo

### ISSUE THREAD

**Issue by ferranmafe** [yuxng/PoseCNN#48]
Hi! Im having the following problem while running the demo:
```
Traceback (most recent call last):
  File "./tools/demo.py", line 84, in <module>
    imdb = get_imdb(args.imdb_name)
  File "/home/fmartinez/ERL/PoseCNN/tools/../lib/datasets/factory.py", line 116, in get_imdb
    return __sets[name]()
  File "/home/fmartinez/ERL/PoseCNN/tools/../lib/datasets/factory.py", line 57, in <lambda>
    datasets.lov(split))
  File "/home/fmartinez/ERL/PoseCNN/tools/../lib/datasets/lov.py", line 55, in __init__
    'Data path does not exist: {}'.format(self._data_path)
AssertionError: Data path does not exist: /home/fmartinez/ERL/PoseCNN/tools/../lib/datasets/../../data/LOV/data
```
Any idea of what should I do?

**Comment by Kaju-Bubanja** [comment]
Just create the folder
