### ISSUE TITLE
When loading gradient_reversal_layer.so SyntaxError: invalid syntax happens?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [yuxng/PoseCNN#49]
I'm trying to run the demo and this I get following stack trace: 

```
Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/<username>/external_libraries_and_code/PoseCNN/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/<username>/external_libraries_and_code/PoseCNN/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/<username>/external_libraries_and_code/PoseCNN/tools/../lib/networks/network.py", line 23, in <module>
    import gradient_reversal_layer.gradient_reversal_op as gradient_reversal_op
  File "/home/<username>/external_libraries_and_code/PoseCNN/tools/../lib/gradient_reversal_layer/gradient_reversal_op.py", line 6, in <module>
    _gradient_reversal_module = tf.load_op_library(filename)
  File "/home/<username>/tf/source_tf/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 58
    "lambda", lambda)
                    ^
SyntaxError: invalid syntax

```

Any idea why this might be happening? It might have to do with the tf version, what tf version did you use, I tried 1.10.0-rc1

**Comment by Kaju-Bubanja** [comment]
It works only with tf version 1.8 built from source neither 1.9 or 1.10 worked.

**Comment by user-vm** [comment]
I think I might've fixed it. There's some variable in the gradient reversal op called "lambda" which seems to clash with Python's "lambda" keyword. Changing $ROOT/lib/gradient_reversal_layer/gradient_reversal_op.cc and $ROOT/lib/gradient_reversal_layer/gradient_reversal_op_grad.py allowed me to run the demo after re-running `sh make.sh`.

```
--- a/lib/gradient_reversal_layer/gradient_reversal_op.cc
+++ b/lib/gradient_reversal_layer/gradient_reversal_op.cc
@@ -29,13 +29,13 @@ typedef Eigen::ThreadPoolDevice CPUDevice;
 
 REGISTER_OP("Gradientreversal")
     .Attr("T: {float, double}")
-    .Attr("lambda: float")
+    .Attr("lmbda: float")
     .Input("bottom_data: T")
     .Output("top_data: T");
 
 REGISTER_OP("GradientreversalGrad")
     .Attr("T: {float, double}")
-    .Attr("lambda: float")
+    .Attr("lmbda: float")
     .Input("bottom_data: T")
     .Input("grad: T")
     .Output("output: T");
@@ -46,7 +46,7 @@ class GradientreversalOp : public OpKernel {
   explicit GradientreversalOp(OpKernelConstruction* context) : OpKernel(context) {
     // Get the lambda
     OP_REQUIRES_OK(context,
-                   context->GetAttr("lambda", &lambda_));
+                   context->GetAttr("lmbda", &lambda_));
     // Check that lambda is positive
     OP_REQUIRES(context, lambda_ > 0,
                 errors::InvalidArgument("Need lambda > 0, got ", lambda_));
@@ -105,10 +105,10 @@ class GradientreversalOp<Eigen::GpuDevice, T> : public OpKernel {
   {
     // Get the lambda
     OP_REQUIRES_OK(context,
-                   context->GetAttr("lambda", &lambda_));
+                   context->GetAttr("lmbda", &lambda_));
     // Check that lambda is positive
     OP_REQUIRES(context, lambda_ > 0,
-                errors::InvalidArgument("Need lambda > 0, got ", lambda_));
+                errors::InvalidArgument("Need lmbda > 0, got ", lambda_));
   }
 
   void Compute(OpKernelContext* context) override 
@@ -157,7 +157,7 @@ class GradientreversalGradOp : public OpKernel {
   {
     // Get the lambda
     OP_REQUIRES_OK(context,
-                   context->GetAttr("lambda", &lambda_));
+                   context->GetAttr("lmbda", &lambda_));
     // Check that lambda is positive
     OP_REQUIRES(context, lambda_ > 0,
                 errors::InvalidArgument("Need lambda > 0, got ", lambda_));
```

```
--- a/lib/gradient_reversal_layer/gradient_reversal_op_grad.py
+++ b/lib/gradient_reversal_layer/gradient_reversal_op_grad.py
@@ -12,7 +12,7 @@ def _gradient_reversal_shape(op):
 def _gradient_reversal_grad(op, grad):
 
   bottom_data = op.inputs[0]
-  lambda_ = op.get_attr('lambda')
+  lambda_ = op.get_attr('lmbda')
 
   # compute gradient
   data_grad = gradient_reversal_op.gradient_reversal_grad(bottom_data, grad, lambda_)
```

Not sure if this breaks anything anywhere else.
