### ISSUE TITLE
Training : No such File or directory "SUN2012"

### ISSUE THREAD

**Issue by TotoLulu94** [yuxng/PoseCNN#58]
Hi @yuxng ,
I tried to train the network using the script "lov_color_2d_train.sh". However, I have the following error : 
`OSError : [Errno 2] No such file or directory : `$ROOT/data/cache/../SUN2012/data/Images' 
There's indeed no directory SUN2012 but I didn't see anything about a SUN2012 folder in you explanation. What does it correspond to ? 

best,

Thomas

**Comment by TotoLulu94** [comment]
The entire error is : ```

Traceback (most recent call last):
  File "./tools/train_net.py", line 336, in <module>
    max_iters=args.max_iters)
  File "/home/thomas/Desktop/Master_Project/PoseCNN/tools/../lib/fcn/train.py", line 544, in train_net
    data_layer = GtSynthesizeLayer(roidb, imdb.num_classes, imdb._extents, imdb._points_all, imdb._symmetry, imdb.cache_path, imdb.name, imdb.data_queue, cfg.CAD, cfg.POSE)
  File "/home/thomas/Desktop/Master_Project/PoseCNN/tools/../lib/gt_synthesize_layer/layer.py", line 36, in __init__
    self._build_background_images()
  File "/home/thomas/Desktop/Master_Project/PoseCNN/tools/../lib/gt_synthesize_layer/layer.py", line 137, in _build_background_images
    subdirs = os.listdir(root)
OSError: [Errno 2] No such file or directory: '/home/thomas/Desktop/Master_Project/PoseCNN/data/cache/../SUN2012/data/Images
```

`

**Comment by sedlaj45** [comment]
Hi Thomas,
I suppose it refers to the SUN Database:
https://groups.csail.mit.edu/vision/SUN/
There's a link to SUN2012.

**Comment by TotoLulu94** [comment]
Thanks !
