### ISSUE TITLE
TypeError: hough_voting_gpu() takes exactly 7 arguments (6 given)

### ISSUE THREAD

**Issue by Kaju-Bubanja** [yuxng/PoseCNN#61]
When trying to run lov_color_2d_train_full.sh I get following error: `TypeError: hough_voting_gpu() takes exactly 7 arguments (6 given)` but I'm not sure what I need to change, I didn't change anything in the code, does this maybe have to do with the tf version? I'm using 1.8. Any ideas what this error could be?
Here a full stacktrace:
```
Traceback (most recent call last):
  File "./tools/train_net.py", line 319, in <module>
    from networks.factory import get_network
  File "$Home/PycharmProjects/PoseCNN/tools/../lib/networks/__init__.py", line 16, in <module>
    from . import factory
  File "$Home/PycharmProjects/PoseCNN/tools/../lib/networks/factory.py", line 31, in <module>
    cfg.TRAIN.MATCHING, cfg.TRAIN.TRAINABLE, cfg.IS_TRAIN)
  File "$Home/PycharmProjects/PoseCNN/tools/../lib/networks/vgg16_full.py", line 70, in __init__
    self.setup()
  File "$Home/PycharmProjects/PoseCNN/tools/../lib/networks/vgg16_full.py", line 170, in setup
    .hough_voting_gpu(self.is_train, -1, self.skip_pixels, name='hough'))
  File "$Home/PycharmProjects/PoseCNN/tools/../lib/networks/network.py", line 52, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
TypeError: hough_voting_gpu() takes exactly 7 arguments (6 given)
```

**Comment by Kaju-Bubanja** [comment]
I fixed this in my fork, basically look at vgg16_convs and how it is done there and then you can copy it to vgg16_full
