### ISSUE TITLE
Error executing ./experiments/scripts/demo.sh $0

### ISSUE THREAD

**Issue by FionaFN** [yuxng/PoseCNN#84]
Error information is as follows:

Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/fiona/FromGithub/PoseCNN/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/fiona/FromGithub/PoseCNN/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/fiona/FromGithub/PoseCNN/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/fiona/FromGithub/PoseCNN/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/home/fiona/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/fiona/FromGithub/PoseCNN/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Do you have any idea about what this might be caused and how to solve this kind of issue?
Thanks so much!!!

My configuration is:
Ubuntu 16.04
CUDA 8
Tensorflow 1.12.0
cmake 3.14.0-rc2
gcc 5.4.0

**Comment by FionaFN** [comment]
I solved it by downgrading Tensorflw to 1.2.0
