### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: <exception str() failed>  :   when trying demo 

### ISSUE THREAD

**Issue by hamza-04** [yuxng/PoseCNN#87]
this is console answer :
Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/hamza/Téléchargements/PoseCNN-master/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/hamza/Téléchargements/PoseCNN-master/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/hamza/Téléchargements/PoseCNN-master/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/hamza/Téléchargements/PoseCNN-master/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/home/hamza/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/hamza/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: <exception str() failed>

i really don't know , if it is matter of path that i should change or something missing with tensorflow , 
Actually i'm trying the demo with the command line :  ./experiments/scripts/demo.sh $GPU_ID

**Comment by hamza-04** [comment]
Actually for those having the same problem , you should add to gcc and nccv in make.sh add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
