### ISSUE TITLE
Error running demo.sh

### ISSUE THREAD

**Issue by Nathan-81** [yuxng/PoseCNN#92]
Hi,
I have a problem running the demo: 
Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I saw that this question had already been asked, but I couldn't find a solution for myself.
I'm on ubuntu 18.04, with Cuda 10.0 and tensorflow 1.13.1.
I thank you in advance for your help

**Comment by Nathan-81** [comment]
Well, as it was suggested in another post I uninstalled tensorflow 1.13.1 and I installed it from source (1.13.1) and now I have the following error : 

tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

Anyone has gotten the same error and solved it?

**Comment by Nathan-81** [comment]
Update : I add the direction to my LD_LIBRARY_PATH and now I get a similar error to the first one : 

Traceback (most recent call last):
  File "./tools/demo.py", line 118, in <module>
    from networks.factory import get_network
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/__init__.py", line 8, in <module>
    from .vgg16 import vgg16
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/vgg16.py", line 2, in <module>
    from networks.network import Network
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/networks/network.py", line 6, in <module>
    import backprojecting_layer.backprojecting_op as backproject_op
  File "/home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting_op.py", line 5, in <module>
    _backprojecting_module = tf.load_op_library(filename)
  File "/home/wongch79/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/wongch79/Programming/6dposeest-posecnn/tools/../lib/backprojecting_layer/backprojecting.so: undefined symbol: _ZTVN10tensorflow14kernel_factory17OpKernelRegistrar18PtrOpKernelFactoryE

**Comment by Spyrko** [comment]
did you find a solution for this problem?
